var w2 = document.createElement('div');
w2.innerHTML = 'dev mode';
w2.style.background = 'yellowgreen';
w2.style.color = '#fff';
w2.style.borderRadius = '2px';
w2.style.padding = '0px 10px';
w2.style.position = 'fixed';
w2.style.bottom = '2px'; 
w2.style.right = '2px'; 
w2.style.zIndex = '99999'; 
document.body.appendChild(w2);
