// 公共样式
export const commonStyle = {
  rotate: 0,
  opacity: 1,
};

export const commonAttr = {
  animations: [],
  events: {},
  groupStyle: {}, // 当一个组件成为 Group 的子组件时使用
  isLock: false, // 是否锁定组件
};

// 编辑器左侧组件列表
const list = [
  {
    component: "v-text",
    label: "姓名",
    caption: "姓名",
    fileId: "patient_name",
    propValue: "姓名:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 165,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "年龄",
    caption: "年龄",
    fileId: "patient_age",
    propValue: "年龄:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 165,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "性别",
    caption: "性别",
    fileId: "patient_gender",
    propValue: "性别:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 165,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      lineHeight: "",
      letterSpacing: 0,
      textAlign: "",
      color: "",
    },
  },
  {
    component: "v-text",
    label: "住院号",
    caption: "住院号",
    fileId: "inhospital_no",
    propValue: "住院号:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 185,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "孕周",
    caption: "孕周",
    fileId: "gestation_week",
    propValue: "孕周:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 165,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "电话",
    caption: "电话",
    fileId: "patient_phone",
    propValue: "电话:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 165,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "病史",
    caption: "病史",
    fileId: "medical_history",
    propValue: "病史:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 165,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "病历编号",
    caption: "病历编号",
    fileId: "patient_no",
    propValue: "病历编号:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "样本编号",
    caption: "样本编号",
    fileId: "patient_id",
    propValue: "样本编号:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "产前编号",
    caption: "产前编号",
    fileId: "prenatal_no",
    propValue: "产前编号:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "健康号",
    caption: "健康号",
    fileId: "health_no",
    propValue: "健康号:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 185,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "附加描述",
    caption: "附加描述",
    fileId: "patient_comment",
    propValue: "附加描述:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "rect-shape",
    label: "中期分裂相图",
    caption: "中期分裂相图",
    propValue: "中期分裂相图",
    fileId: "karyotype_image",
    type: "image",
    value: "",
    style: {
      width: 150,
      height: 150,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
      lineHeight: "",
      letterSpacing: 0,
      textAlign: "center",
      color: "",
      borderColor: "#000",
      borderWidth: 1,
      backgroundColor: "",
      borderStyle: "solid",
      borderRadius: "",
      verticalAlign: "middle",
    },
  },
  {
    component: "rect-shape",
    label: "排列图",
    caption: "排列图",
    propValue: "排列图",
    fileId: "arrange_image",
    type: "image",
    value: "",
    style: {
      width: 150,
      height: 150,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
      lineHeight: "",
      letterSpacing: 0,
      textAlign: "center",
      color: "",
      borderColor: "#000",
      borderWidth: 1,
      backgroundColor: "",
      borderStyle: "solid",
      borderRadius: "",
      verticalAlign: "middle",
    },
  },
  {
    component: "v-text",
    label: "核型表达式",
    caption: "核型表达式",
    fileId: "karyotype_expression",
    propValue: "核型表达式:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 210,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "计数细胞数",
    caption: "计数细胞数",
    fileId: "cell_count_number",
    propValue: "计数细胞数:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 210,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "排列细胞数",
    caption: "排列细胞数",
    fileId: "cell_arrange_number",
    propValue: "排列细胞数:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 210,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "细胞总数",
    caption: "细胞总数",
    fileId: "cell_total",
    propValue: "细胞总数:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "样本类型",
    caption: "样本类型",
    fileId: "sample_type",
    propValue: "样本类型:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "采集时间",
    caption: "采集时间",
    fileId: "collect_time",
    propValue: "采集时间:",
    // icon: 'wenben',
    type: "input_datetime",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "送检医师",
    caption: "送检医师",
    fileId: "send_doctor",
    propValue: "送检医师:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },

  {
    component: "v-text",
    label: "送检科室",
    caption: "送检科室",
    fileId: "send_department",
    propValue: "送检科室:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },

  {
    component: "v-text",
    label: "接收医生",
    caption: "接收医生",
    fileId: "receive_doctor",
    propValue: "接收医生:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "接收时间",
    caption: "接收时间",
    fileId: "receive_time",
    propValue: "接收时间:",
    // icon: 'wenben',
    type: "input_datetime",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },

  {
    component: "v-text",
    label: "检查方法",
    caption: "检查方法",
    fileId: "check_method",
    propValue: "检查方法:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "检验时间",
    caption: "检验时间",
    fileId: "check_time",
    propValue: "检验时间:",
    // icon: 'wenben',
    type: "input_datetime",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "诊断医生",
    caption: "诊断医生",
    fileId: "diagnosis_doctor",
    propValue: "诊断医生:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "审核医生",
    caption: "审核医生",
    fileId: "review_doctor",
    propValue: "审核医生:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "审核时间",
    caption: "审核时间",
    fileId: "review_time",
    propValue: "审核时间:",
    // icon: 'wenben',
    type: "input_datetime",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "诊断描述",
    caption: "诊断描述",
    fileId: "diagnosis_desc",
    propValue: "诊断描述:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "报告时间",
    caption: "报告时间",
    fileId: "report_time",
    propValue: "报告时间:",
    // icon: 'wenben',
    type: "input_datetime",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "机构名称",
    caption: "机构名称",
    fileId: "organization_name",
    propValue: "机构名称:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "诊断标准",
    caption: "诊断标准",
    fileId: "diagnosis_criterion",
    propValue: "诊断标准:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "产前诊断指征",
    caption: "产前诊断指征",
    fileId: "prenatal_features",
    propValue: "产前诊断指征:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 225,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "诊断依据描述",
    caption: "诊断依据描述",
    fileId: "diagnosis_basis",
    propValue: "诊断依据描述:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 225,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "临床描述",
    caption: "临床描述",
    fileId: "clinical_basis",
    propValue: "临床描述:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 225,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "临床诊断",
    caption: "临床诊断",
    fileId: "clinical_diagnosis",
    propValue: "临床诊断:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 225,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    label: "备注",
    caption: "备注",
    fileId: "comment",
    propValue: "备注:",
    // icon: 'wenben',
    type: "input",
    value: "",
    style: {
      underline: 1,
      width: 167,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
    },
  },
  {
    component: "v-text",
    type: "text",
    label: "文字",
    propValue: "双击编辑文字",
    icon: "wenben",
    show:true,
    style: {
      underline: 1,
      width: 200,
      height: 22,
      fontSize: 14,fontFamily  :'Microsoft YaHei',
      fontWeight: 500,
      lineHeight: "",
      letterSpacing: 0,
      textAlign: "",
      color: "",
    },
  },
  // {
  //     component: 'Picture',
  //     label: '图片',
  //     icon: 'tupian',
  //     propValue: require('@/assets/title.jpg'),
  //     style: {
  //         width: 300,
  //         height: 200,
  //         borderRadius: '',
  //     },
  // },
  {
    component: "rect-shape",
    type: "rectangle",
    label: "矩形",
    propValue: "&nbsp;",
    icon: "juxing",
    style: {
      width: 200,
      height: 200,
      fontSize: 14,
      fontWeight: 500,
      lineHeight: "",
      letterSpacing: 0,
      textAlign: "center",
      color: "",
      borderColor: "#000",
      borderWidth: 1,
      backgroundColor: "",
      borderStyle: "solid",
      borderRadius: "",
      verticalAlign: "middle",
    },
  },
  {
    component: "rect-shape",
    type: "vertical_line",
    label: "竖线",
    propValue: "&nbsp;",
    style: {
      width: 1,
      height: 200,
      letterSpacing: 0,
      color: "",
      borderColor: "#fff",
      borderRight: "thick dotted #000",
      borderWidth: 1,
      backgroundColor: "",
      borderStyle: "solid",
      borderRadius: "",
      verticalAlign: "middle",
    },
  },
  {
    component: "rect-shape",
    type: "horizontal_line",
    label: "横线",
    propValue: "&nbsp;",
    style: {
      width: 200,
      height: 1,
      letterSpacing: 0,
      color: "",
      borderColor: "#fff",
      borderBottom: "thick dotted #000",
      borderWidth: 1,
      backgroundColor: "",
      borderStyle: "solid",
      borderRadius: "",
      verticalAlign: "middle",
    },
  },
];

for (let i = 0, len = list.length; i < len; i++) {
  const item = list[i];
  item.style = { ...commonStyle, ...item.style };
  list[i] = { ...commonAttr, ...item };
}

export default list;
