export const CODE_COUNTRY_MAP = {
  AP: 'Asia/Pacific Region',
  EU: 'Europe',
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua And Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AN: 'Netherlands Antilles',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AZ: 'Azerbaijan',
  BA: 'Bosnia And Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos (Keeling) Islands',
  CD: 'Democratic Republic Of The Congo',
  CF: 'Central African Republic',
  CG: 'Congo',
  CH: 'Switzerland',
  CI: "Cote D'Ivoire",
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cape Verde',
  CX: 'Christmas Island',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'Western Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands (Malvinas)',
  FM: 'Federated States Of Micronesia',
  FO: 'Faroe Islands',
  FR: 'France',
  FX: 'France Metropolitan',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia And The South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HM: 'Heard Island And Mcdonald Islands',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts And Nevis',
  KP: "Democratic People'S Republic Of Korea",
  KR: 'Republic Of Korea',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: "Lao People'S Democratic Republic",
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macau',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre And Miquelon',
  PN: 'Pitcairn Islands',
  PR: 'Puerto Rico',
  PS: 'Palestine',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  ST: 'Sao Tome And Principe',
  SV: 'El Salvador',
  SY: 'Syria',
  SZ: 'Swaziland',
  TC: 'Turks And Caicos Islands',
  TD: 'Chad',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TL: 'Timor-Leste',
  TR: 'Turkey',
  TT: 'Trinidad And Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Vatican',
  VC: 'Saint Vincent And The Grenadines',
  VE: 'Venezuela',
  VG: 'British Virgin Islands',
  VI: 'U.S. Virgin Islands',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis And Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  RS: 'Serbia',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ME: 'Montenegro',
  ZW: 'Zimbabwe',
  A1: 'Anonymous Proxy',
  A2: 'Satellite Provider',
  O1: 'Other',
  AX: 'Aland Islands',
  GG: 'Guernsey',
  IM: 'Isle Of Man',
  JE: 'Jersey',
  BL: 'Saint Bartelemey',
  MF: 'Saint Martin',
  RESERVED: 'Reserved',
} as const;

export const COUNTRY_CODE_MAP = Object.keys(CODE_COUNTRY_MAP).reduce((acc, code) => {
  return Object.assign(acc, { [CODE_COUNTRY_MAP[code]]: code });
}, {});

export const MAP_REGIONS = [
  { value: 'us-east-1', label: 'US East (N.Virginia)', latitude: 37.44228, longitude: -76.420822 },
  { value: 'us-east-2', label: 'US East (Ohio)', latitude: 40.417286, longitude: -82.90712 },
  { value: 'us-west-1', label: 'US West (N.California)', latitude: 36.778259, longitude: -119.417931 },
  { value: 'us-west-2', label: 'US West (Oregon)', latitude: 43.804134, longitude: -120.554199 },
  { value: 'ap-south-1', label: 'Asia Pacific (Mumbai)', latitude: 19.075983, longitude: 72.877655 },
  { value: 'ap-northeast-2', label: 'Asia Pacific (Seoul)', latitude: 37.566536, longitude: 126.977966 },
  { value: 'ap-southeast-1', label: 'Asia Pacific (Singapore)', latitude: 2.352083, longitude: 103.819839 },
  { value: 'ap-southeast-1.prod', label: 'Asia Pacific (Singapore)', latitude: 2.352083, longitude: 103.819839 },
  { value: 'ap-southeast-1.1', label: 'US East (N.Virginia)', latitude: 39.44228, longitude: -74.420822 }, // this is special, route in N.Virginia, cluster in Singapore
  { value: 'ap-northeast-2.1', label: 'US East (N.Virginia)', latitude: 39.44228, longitude: -74.420822 }, // this is special, route in N.Virginia, cluster in Seoul
  { value: 'ap-southeast-2', label: 'Asia Pacific (Sydney)', latitude: -33.86882, longitude: 151.20929 },
  { value: 'ap-northeast-1', label: 'Asia Pacific (Tokyo)', latitude: 35.689487, longitude: 139.691711 },
  { value: 'ap-east-1', label: 'Asia Pacific (Hong Kong)', latitude: 22.396427, longitude: 114.109497 },
  { value: 'ca-central-1', label: 'Canada (Central)', latitude: 44.771839, longitude: -76.687042 },
  { value: 'eu-central-1', label: 'EU (Frankfurt)', latitude: 50.110924, longitude: 8.682127 },
  { value: 'eu-west-1', label: 'EU (Ireland)', latitude: 54.41291, longitude: -8.24389 },
  { value: 'eu-west-2', label: 'EU (London)', latitude: 52.507351, longitude: -0.127758 },
  { value: 'eu-west-2.1', label: 'EU (London)', latitude: 51.507351, longitude: -0.127758 },
  { value: 'eu-west-3', label: 'EU (Paris)', latitude: 48.856613, longitude: 2.352222 },
  { value: 'eu-north-1', label: 'EU (Stockholm)', latitude: 59.329323, longitude: 18.068581 },
  { value: 'eu-south-1', label: 'EU (Milan)', latitude: 45.464203, longitude: 9.189982 },
  { value: 'sa-east-1', label: 'South America (São Paulo)', latitude: -23.55052, longitude: -46.633308 },
  { value: 'us-west-1.qa', label: 'US West QA (N.California)', latitude: 36.778259, longitude: -119.417931 },
  { value: 'us-west-2.qa', label: 'US West QA (Oregon)', latitude: 43.804134, longitude: -120.554199 },
  //Azure
  { value: 'southeastasia', label: 'Singapore', latitude: 2.352083, longitude: 103.819839 },
  { value: 'southeastasia.1', label: 'Virginia', latitude: 39.44228, longitude: -74.420822 }, // this is special, route in N.Virginia, cluster in Singapore
  { value: 'southeastasiaprd', label: 'Singapore', latitude: 2.352083, longitude: 103.819839 },
  { value: 'koreacentral', label: 'Seoul', latitude: 37.566536, longitude: 126.977966 },
  { value: 'koreacentral.1', label: 'Virginia', latitude: 39.44228, longitude: -74.420822 }, // this is special, route in N.Virginia, cluster in Seoul
  { value: 'eastus', label: 'Virginia 1', latitude: 37.44228, longitude: -76.420822 },
  { value: 'eastus2', label: 'Virginia 2', latitude: 37.44228, longitude: -76.420822 },
  { value: 'westus', label: 'California', latitude: 36.778259, longitude: -119.417931 },
  { value: 'westus2', label: 'Washington', latitude: 47.751076, longitude: -120.740135 },
  { value: 'centralus', label: 'Iowa', latitude: 42.032974, longitude: -93.581543 },
  { value: 'northcentralus', label: 'Illinois', latitude: 40.0, longitude: -89.0 },
  { value: 'southcentralus', label: 'Texas', latitude: 31.0, longitude: -100.0 },
  { value: 'canadacentral', label: 'Toronto', latitude: 43.653908, longitude: -79.384293 },
  { value: 'northeurope', label: 'Ireland', latitude: 54.41291, longitude: -8.24389 },
  { value: 'uksouth', label: 'London', latitude: 52.507351, longitude: -0.127758 },
  { value: 'uksouth.1', label: 'London', latitude: 51.507351, longitude: -0.127758 },
  { value: 'westeurope', label: 'Netherlands', latitude: 52.370216, longitude: 4.895168 },
  { value: 'francecentral', label: 'Paris', latitude: 48.856613, longitude: 2.352222 },
  { value: 'australiaeast', label: 'New South Wales', latitude: -33.86882, longitude: 151.20929 },
  { value: 'brazilsouth', label: 'Sao Paulo', latitude: -23.55052, longitude: -46.633308 },
  //C8T
  { value: 'Taiwan_country', label: 'Taiwan', latitude: 23.05, longitude: 121.5, color: 'orange' }, // this is specail handle Taiwan as a country
  { value: 'c8t-dev', label: 'Taiwan', latitude: 25.05, longitude: 121.5 },
  { value: 'c8t-qa', label: 'Taiwan', latitude: 25.05, longitude: 121.5 },
  { value: 'c8t-taiwan', label: 'Taiwan', latitude: 25.05, longitude: 121.5 },
  { value: 'c8t-poc', label: 'Taiwan', latitude: 25.05, longitude: 121.5 },
  { value: 'c8t-manila', label: 'Manila', latitude: 14.361512, longitude: 120.585592 },
  //GCP
  { value: 'asia-southeast1', label: 'Asia Southeast (Singapore)', latitude: 2.352083, longitude: 103.819839 },
  { value: 'asia-southeast1.1', label: 'US East 1 (South Carolina)', latitude: 33.836082, longitude: -81.163727 },
  { value: 'asia-east1', label: 'Asia Northeast (Taiwan)', latitude: 25.05, longitude: 121.5 },
  { value: 'asia-east1.1', label: 'Asia Northeast (Tokyo)', latitude: 35.689487, longitude: 139.691711 },
  { value: 'europe-west2', label: 'Europe West 2 (London)', latitude: 52.507351, longitude: -0.127758 },
  { value: 'us-east1', label: 'US East 1 (South Carolina)', latitude: 33.836082, longitude: -81.163727 },
  { value: 'us-west1', label: 'US West 1 (Oregon)', latitude: 43.804134, longitude: -120.554199 },
  { value: 'europe-west3', label: 'Europe West 3 (Frankfurt)', latitude: 50.110924, longitude: 8.682127 },
  { value: 'europe-west8', label: 'Europe West 8 (Milan)', latitude: 45.464203, longitude: 9.189982 },
  //OCI
  { value: 'ap-tokyo-1', label: 'Japan East (Tokyo)', latitude: 35.689487, longitude: 139.691711 },
  { value: 'ap-seoul-1', label: 'South Korea Central (Seoul)', latitude: 37.566536, longitude: 126.977966 },
  { value: 'us-ashburn-1', label: 'US East (Ashburn)', latitude: 39.043758, longitude: -77.487442 },
  { value: 'us-phoenix-1', label: 'US West (Phoenix)', latitude: 33.448376, longitude: -112.074036 },
  { value: 'eu-frankfurt-1', label: 'Europe West (Frankfurt)', latitude: 50.110924, longitude: 8.682127 },
  //Location of National Points on Maps (Countries to which the above region cities belong)
  { value: 'United States', label: 'United States', latitude: 38.878259, longitude: -100.417931 },
  { value: 'India', label: 'India', latitude: 24.075983, longitude: 78.077655 },
  { value: 'Republic Of Korea', label: 'Republic Of Korea', latitude: 36.366536, longitude: 128.077966 },
  { value: 'Singapore', label: 'Singapore', latitude: 1.352083, longitude: 103.819839 },
  { value: 'Australia', label: 'Australia', latitude: -24.02882, longitude: 134.40929 },
  { value: 'Japan', label: 'Japan', latitude: 36.139487, longitude: 137.391711 },
  { value: 'Canada', label: 'Canada', latitude: 60.331839, longitude: -115.3287042 },
  { value: 'Germany', label: 'Germany', latitude: 52.310924, longitude: 10.682127 },
  { value: 'Ireland', label: 'Ireland', latitude: 53.32991, longitude: -8.24389 },
  { value: 'United Kingdom', label: 'United Kingdom', latitude: 52.507351, longitude: -1.487758 },
  { value: 'France', label: 'France', latitude: 47.642613, longitude: 1.395222 },
  { value: 'Sweden', label: 'Sweden', latitude: 62.749323, longitude: 16.278581 },
  { value: 'Brazil', label: 'Brazil', latitude: -8.55052, longitude: -52.633308 },
  { value: 'Philippines', label: 'Philippines', latitude: 16.361512, longitude: 121.085592 },
  { value: 'Netherlands', label: 'Netherlands', latitude: 53.070216, longitude: 6.595168 },
];
