/**
 * Menu config example
 * [{
 * 	// non-leaf node, have children, no serf
 * 	label: 'Security Rules',
 * 	id: 'security_rules',
 * 	icon: 'nucleo-icon icon-security-rules',
 * 	children: [{
 * 		// leaf node, have a serf
 * 		label: 'Known Attacks',
 * 		sref: 'root.application.knownattacks',
 * 		mini: 'KA',
 * 		id: 'knownattacks',
 * 		config: true, // whether this module is configurable, only work with leaf node
 * 		default: true, // whether this module is default module, only work when config=true
 * 		desc: 'Protect against known attacks.' // module description, needed when config=true
 * 	}]
 * }]
 */
interface MenuItem {
  label: string;
  id: string;
  sref?: string;
  icon?: string;
  global?: boolean;
  children?: MenuItem[];
  mini?: string;
  config?: boolean;
  default?: boolean;
  template?: boolean;
  tplsref?: string;
  desc?: string;
}

export const FWC_MENU: MenuItem[] = [
  {
    label: 'MSSP Portal',
    id: 'mssp',
    global: true,
    children: [
      {
        label: 'Tenant Management',
        id: 'tenantmanagement',
        sref: 'root.tenantmanagement',
        mini: 'TM',
      },
      {
        label: 'Contract Management',
        id: 'contractmanagement',
        sref: 'root.contractmanagement',
        mini: 'CM',
      },
    ],
  },
  {
    label: 'Global',
    id: 'global',
    icon: 'ti-world',
    global: true,
    children: [
      {
        label: 'Applications',
        id: 'applications',
        sref: 'root.applications',
        mini: 'A',
      },
      {
        label: 'Templates',
        id: 'templates',
        sref: 'root.templates',
        mini: 'T',
      },
      {
        label: 'Administrators',
        id: 'administrators',
        icon: '',
        mini: 'A',
        children: [
          {
            label: 'Admin Management',
            id: 'adminmanagement',
            sref: 'root.adminmanagement',
            mini: 'am',
          },
          {
            label: 'Role Management',
            id: 'rolemanagement',
            sref: 'root.rolemanagement',
            mini: 'rm',
          },
        ],
      },
      {
        label: 'System Settings',
        id: 'system_settings',
        icon: '',
        mini: 'SS',
        children: [
          {
            label: 'Settings',
            id: 'settings',
            sref: 'root.settings',
            mini: 's',
          },
          {
            label: 'Contracts',
            id: 'contracts',
            sref: 'root.contracts',
            mini: 'c',
          },
          {
            label: 'Cloud Connectors',
            id: 'fabric_connectors',
            sref: 'root.cloud_connectors',
            mini: 'cc',
          },
          {
            label: 'Custom Block Pages',
            id: 'custom_block_page',
            sref: 'root.custom_block_page',
            mini: 'cbp',
          },
        ],
      },
      {
        label: 'Log & Report',
        id: 'log_n_report',
        icon: '',
        mini: 'LR',
        children: [
          {
            label: 'Audit Logs',
            id: 'auditlogs',
            sref: 'root.elogs',
            mini: 'al',
          },
          {
            label: 'Reports',
            id: 'reports',
            sref: 'root.reports',
            mini: 'r',
          },
        ],
      },
    ],
  },
  {
    label: 'Threat Analytics',
    id: 'threat_analytics_group',
    global: true,
    icon: 'ti-pulse',
    children: [
      {
        label: 'Threat Analytics',
        id: 'threat_analytics',
        sref: 'root.incidentMonitor({ tab: 0 })',
        mini: 'TA',
      },
      {
        label: 'Attack Logs',
        id: 'attack_logs',
        sref: 'root.attacklogs',
        mini: 'AL',
      },
      {
        label: 'WAF Gateways',
        id: 'waf_gateways',
        sref: 'root.wafgateways',
        mini: 'WG',
      },
    ],
  },
  {
    label: 'Dashboard',
    id: 'dashboard',
    icon: 'ti-dashboard',
    // sref: 'root.application.overview'
    sref: 'root.application.dashboard',
  },
  {
    label: 'Log Settings',
    id: 'attack_log_export',
    icon: 'ti-settings',
    sref: 'root.application.attacklogexport',
    desc: 'attack_log_settings_description',
  },
  {
    label: 'fortiview',
    id: 'fortiview',
    icon: 'ti-list',
    children: [
      {
        label: 'Threat by OWASP TOP10',
        id: 'owasptop10',
        sref: 'root.application.fortiview.owasptop10',
        mini: 'TO',
      },
      {
        label: 'Threat by Types',
        id: 'threat',
        sref: 'root.application.fortiview.threat',
        mini: 'TT',
      },
      {
        label: 'Threat by Source IPs',
        id: 'source',
        sref: 'root.application.fortiview.source',
        mini: 'TS',
      },
      {
        label: 'Threat by Countries',
        id: 'country',
        sref: 'root.application.fortiview.country',
        mini: 'TC',
      },
      {
        label: 'Threat by CVE ID',
        id: 'signature_cve_id',
        sref: 'root.application.fortiview.signature_cve_id',
        mini: 'TCV',
      },
      {
        label: 'Threat Map',
        id: 'threatmap',
        sref: 'root.application.fortiviewMap',
        mini: 'TM',
      },
      {
        label: 'Traffic Summary',
        id: 'trafficsummary',
        sref: 'root.application.trafficsummary',
        mini: 'TS',
      },
    ],
  },
  {
    label: 'NETWORK',
    id: 'network',
    icon: 'ti-view-list-alt',
    children: [
      {
        label: 'Endpoints',
        sref: 'root.application.endpoints',
        mini: 'E',
        id: 'endpoints',
      },
      {
        label: 'Origin Servers',
        sref: 'root.application.servers',
        mini: 'OS',
        id: 'servers',
      },
    ],
  },
  {
    label: 'Security Rules',
    id: 'security_rules',
    icon: 'nucleo-icon icon-security-rules',
    children: [
      {
        label: 'Known Attacks',
        sref: 'root.application.known_attacks',
        mini: 'KA',
        id: 'known_attacks',
        config: true,
        default: true,
        template: true,
        tplsref: 'root.template.known_attacks',
        desc: 'Protect against known attacks, common vulnerabilities and exposures (CVEs) and other exploits that are part of the OWASP Top 10.',
      },
      {
        label: 'Anomaly Detection',
        sref: 'root.application.anomaly_detection',
        mini: 'AD',
        id: 'anomaly_detection',
        config: true,
        default: true,
        template: true,
        tplsref: 'root.template.anomaly_detection',
        desc: 'anomaly_detection_desc',
      },
      {
        label: 'Information Leakage',
        sref: 'root.application.information_leakage',
        mini: 'IL',
        id: 'information_leakage',
        config: true,
        template: true,
        tplsref: 'root.template.information_leakage',
        desc: 'Information Leakage is the process of sensitive data leaking from the server. This can be server information that allows attackers to gather information that can help in future attacks.',
      },
      {
        label: 'Cookie Security',
        sref: 'root.application.cookie_security',
        mini: 'CS',
        id: 'cookie_security',
        config: true,
        template: true,
        tplsref: 'root.template.cookie_security',
        desc: 'Protect against Cookie poisoning that can lead to stolen sensitive data and account takeover.',
      },
      {
        label: 'File Protection',
        sref: 'root.application.file_protection',
        mini: 'FP',
        id: 'file_protection',
        config: true,
        template: true,
        tplsref: 'root.template.file_protection',
        desc: 'File protection verifies that all files uploaded to the application are safe and follow size and type guidelines.',
      },
      {
        label: 'Parameter Validation',
        sref: 'root.application.parameter_validation',
        mini: 'PV',
        id: 'parameter_validation',
        config: true,
        default: true,
        template: true,
        tplsref: 'root.template.parameter_validation',
        desc: 'You can configure rules to validate parameters (input) of your web applications. Input rules define whether or not parameters are required, and their maximum allowed length, whether or not they match pre-defined/customized patterns.',
      },
    ],
  },
  {
    label: 'Client Security',
    id: 'client_security',
    icon: 'nucleo-icon icon-touch-id',
    children: [
      {
        label: 'HTTP Header Security',
        sref: 'root.application.http_header_security',
        mini: 'HHS',
        id: 'http_header_security',
        config: true,
        template: true,
        tplsref: 'root.template.http_header_security',
        desc: 'HTTP response security headers are a set of standard HTTP response headers that can help mitigate known XSS, clickjacking, and MIME sniffing security vulnerabilities. These response headers define security policies to client browsers so that the browsers avoid exposure to known vulnerabilities when handling requests.',
      },
      {
        label: 'CSRF Protection',
        sref: 'root.application.csrf_protection',
        mini: 'CP',
        id: 'csrf_protection',
        config: true,
        template: true,
        tplsref: 'root.template.csrf_protection',
        desc: 'csrf_desc',
      },
      {
        label: 'MITB Protection',
        sref: 'root.application.mitb_protection',
        mini: 'MP',
        id: 'mitb_protection',
        config: true,
        template: true,
        tplsref: 'root.template.mitb_protection',
        desc: 'mitb_protection_description',
      },
    ],
  },
  {
    label: 'Access Rules',
    id: 'access_rule',
    icon: 'nucleo-icon icon-key-25',
    children: [
      {
        label: 'Request Limits',
        sref: 'root.application.request_limits',
        mini: 'RL',
        id: 'request_limits',
        config: true,
        default: true,
        template: true,
        tplsref: 'root.template.request_limits',
        desc: 'Request Limits enforce limitations at the HTTP protocol level to make sure all client requests adhere to the HTTP RFC standard and security best practice. By using Request Limits you can prevent exploits such as malicious encoding and buffer overflows that can lead to Denial of Service (DoS) and server takeover.',
      },
      {
        label: 'URL Access',
        sref: 'root.application.url_access',
        mini: 'UA',
        id: 'url_access',
        config: true,
        template: true,
        tplsref: 'root.template.url_access',
        desc: 'Control client access based on requested URL',
      },
      {
        label: 'IP Protection',
        sref: 'root.application.ip_protection',
        mini: 'IP',
        id: 'ip_protection',
        config: true,
        template: true,
        tplsref: 'root.template.ip_protection',
        desc: 'Allow or deny access based on source IP restrictions.',
      },
      {
        label: 'CORS Protection',
        sref: 'root.application.cors_protection',
        mini: 'IP',
        id: 'cors_protection',
        config: true,
        template: true,
        tplsref: 'root.template.cors_protection',
        desc: 'cors_protection_description',
      },
    ],
  },
  {
    label: 'Bot Mitigation',
    id: 'bot_mitigation',
    icon: 'ti-themify-favicon',
    children: [
      {
        label: 'Known Bots',
        sref: 'root.application.known_bots',
        id: 'known_bots',
        mini: 'KB',
        config: true,
        template: true,
        tplsref: 'root.template.known_bots',
        desc: 'known_bots_description',
      },
      {
        label: 'Threshold Based Detection',
        sref: 'root.application.threshold_detection',
        id: 'threshold_detection',
        mini: 'TB',
        config: true,
        template: true,
        tplsref: 'root.template.threshold_detection',
        desc: 'bot_threshold_baseddetection_description',
      },
      {
        label: 'ML Based Bot Detection',
        sref: 'root.application.ml_bot_detection',
        id: 'ml_bot_detection',
        mini: 'MBD',
        config: true,
        template: true,
        tplsref: 'root.template.ml_bot_detection',
        desc: 'machine_learning_bot_detection_description',
      },
      {
        label: 'Biometrics Based Detection',
        sref: 'root.application.biometrics_based_detection',
        id: 'biometrics_based_detection',
        mini: 'BB',
        config: true,
        template: true,
        tplsref: 'root.template.biometrics_based_detection',
        desc: 'bot_biometrics_baseddetection_description',
      },
      {
        label: 'Bot Deception',
        sref: 'root.application.bot_deception',
        id: 'bot_deception',
        mini: 'BD',
        config: true,
        template: true,
        tplsref: 'root.template.bot_deception',
        desc: 'bot_deception_description',
      },
    ],
  },
  {
    label: 'ddos_prevention_title',
    id: 'ddos_prevention',
    icon: 'ti-shield',
    sref: 'root.application.ddos_prevention',
    config: true,
    default: true,
    template: true,
    tplsref: 'root.template.ddos_prevention',
    desc: 'ddos_prevention_description',
  },
  {
    label: 'Advanced Applications',
    icon: 'nucleo-icon icon-umbrella-13',
    id: 'advanced_application',
    children: [
      {
        label: 'Custom Rule',
        sref: 'root.application.custom_rule',
        mini: 'CR',
        id: 'custom_rule',
        config: true,
        template: true,
        tplsref: 'root.template.custom_rule',
        desc: 'Custom rules provide advanced access control capabilities to match complex conditions specific to your web application',
      },
      {
        label: 'WebSocket Security',
        sref: 'root.application.web_socket_security',
        mini: 'WS',
        id: 'web_socket_security',
        config: true,
        template: true,
        tplsref: 'root.template.web_socket_security',
        desc: 'websocket_desc',
      },
    ],
  },
  {
    label: 'API Protection',
    icon: 'nucleo-icon icon-advanced-applications',
    id: 'api',
    children: [
      {
        label: 'OpenAPI Validation',
        sref: 'root.application.api_protection',
        mini: 'AP',
        id: 'api_protection',
        config: true,
        template: true,
        tplsref: 'root.template.api_protection',
        desc: 'OpenAPI is a standard to describe APIs. Enable to enforce all access to the API based on the definitions described in OpenAPI file',
      },
      {
        label: 'API Gateway',
        sref: 'root.application.api_gateway',
        mini: 'AG',
        id: 'api_gateway',
        config: true,
        template: true,
        tplsref: 'root.template.api_gateway',
        desc: 'API Gateway allows to manage API users, verify API keys, control API access and rate limits, as well as rewrite API calls.',
      },
      {
        label: 'Mobile API Protection',
        sref: 'root.application.mobile_api_protection',
        mini: 'MAP',
        id: 'mobile_api_protection',
        config: true,
        template: true,
        tplsref: 'root.template.mobile_api_protection',
        desc: 'Mobile API Protection verifies whether the request from a mobile application carries a valid JWT-token.',
      },
      {
        label: 'JSON Protection',
        sref: 'root.application.json_protection',
        mini: 'JP',
        id: 'json_protection',
        config: true,
        template: true,
        tplsref: 'root.template.json_protection',
        desc: 'JSON Protection validates JSON data contents in a JSON document to ensure the contents do not contain any potential attacks.',
      },
      {
        label: 'XML Protection',
        sref: 'root.application.xml_protection_policy',
        mini: 'XP',
        id: 'xml_protection_policy',
        config: true,
        template: true,
        tplsref: 'root.template.xml_protection_policy',
        desc: 'XML is commonly used for data exchange between two applications and while it is vulnerable to the same risks as standard web applications it also has a variety of service specific vulnerabilities',
      },
      {
        label: 'ML Based API Protection',
        sref: 'root.application.ml_api_protection',
        mini: 'MAP',
        id: 'ml_api_protection',
        config: true,
        template: true,
        tplsref: 'root.template.ml_api_protection',
        desc: "Use Machine Learning Based API protection to prevent malicious API requests to your application's resources. The machine learning model evaluates real time API requests and then takes corresponding actions to block alert, etc.",
      },
    ],
  },
  {
    label: 'Account Takeover',
    id: 'account_takeover',
    icon: 'nucleo-icon icon-single-02',
    sref: 'root.application.accounttakeover',
    config: true,
    template: true,
    tplsref: 'root.template.accounttakeover',
    desc: 'account_takeover_desc',
  },
  {
    label: 'Application Delivery',
    icon: 'nucleo-icon icon-cloud-upload-94',
    id: 'application_delivery',
    children: [
      {
        label: 'Rewriting Requests',
        sref: 'root.application.rewriting_requests',
        mini: 'RR',
        id: 'rewriting_requests',
        config: true,
        template: true,
        tplsref: 'root.template.rewriting_requests',
        desc: 'Rewriting URLs and headers allows changing the structure of the request from clients before forwarding to the web application. Use the below to Rewrite, Insert headers or Redirect requests.',
      },
      {
        label: 'Caching and Compression',
        sref: 'root.application.caching_compression',
        mini: 'CC',
        id: 'caching_compression',
        config: true,
        default: true,
        template: true,
        tplsref: 'root.template.caching_compression',
        desc: 'Optimize performance by enabling Caching and Compression.',
      },
      {
        label: 'Waiting Room',
        sref: 'root.application.waiting_room',
        mini: 'WR',
        id: 'waiting_room',
        config: true,
        default: true,
        template: true,
        tplsref: 'root.template.waiting_room',
        desc: 'waiting_room_desc',
      },
    ],
  },
  {
    label: 'Global Trustlist',
    icon: 'nucleo-icon icon-paper',
    id: 'global_trust_list_parameter',
    sref: 'root.application.global_trust_list_parameter',
    config: true,
    desc: 'Exclude the specified parameters from being scanned across the entire application.',
  },
  {
    label: 'Vulnerability Scan',
    id: 'VulnerabilityScan',
    icon: 'ti-flag-alt',
    sref: 'root.application.vulnerabilityscan',
    config: false,
    default: true,
    template: false,
    desc: 'vulnerability_scan_description',
  },
];
